// <auto-generated />
namespace GNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_path_currentcappacity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_path_currentcappacity));
        
        string IMigrationMetadata.Id
        {
            get { return "202101151008305_add_path_currentcappacity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
