// <auto-generated />
namespace GNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sub_add_FK_to_path : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sub_add_FK_to_path));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141607131_sub_add_FK_to_path"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
