// <auto-generated />
namespace GNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_client));
        
        string IMigrationMetadata.Id
        {
            get { return "202101081820284_add_client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
