// <auto-generated />
namespace GNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REQUIRED_client_name_login_password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REQUIRED_client_name_login_password));
        
        string IMigrationMetadata.Id
        {
            get { return "202101082052086_REQUIRED_client_name_login_password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
