// <auto-generated />
namespace GNA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class compny_nulls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(compny_nulls));
        
        string IMigrationMetadata.Id
        {
            get { return "202101132227355_compny_nulls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
